name: Generate .env File

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  generate-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate .env File
        run: |
          echo "API_KEY=${{ secrets.VAULT_TOKEN }}" >> .env
          
